name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: deps
      run: |
        sudo apt-get install \
          libgtk2.0-dev \
          ladspa-sdk
    - uses: actions/checkout@v3
    - name: bootstrap
      run: autoreconf -vfi
    - name: configure
      run: ./configure
    - name: make distcheck
      run: make distcheck
